---
title: "Emergency"
output:
  pdf_document:
    toc: TRUE
    keep_tex: TRUE
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
  - \makeatletter\renewcommand*{\fps@figure}{H}\makeatother
params:
  dev: TRUE
  package_dir: "."
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
fhi::DashboardInitialiseOpinionated("sykdomspuls",
                                    PACKAGE_DIR=params$package_dir,
                                    FORCE_DEV_PACKAGE_LOAD = params$dev,
                                    SILENT=TRUE)

suppressMessages(library(data.table))
suppressMessages(library(ggplot2))
suppressMessages(library(kableExtra))
suppressMessages(library(fhiplot))
suppressMessages(library(lubridate))
suppressMessages(library(fhidata))


start_date = ymd("2019-01-01")

conn <- DBI::dbConnect(odbc::odbc(),
    driver = CONFIG$DB_CONFIG$driver,
    server = CONFIG$DB_CONFIG$server,
    port = CONFIG$DB_CONFIG$port,
    user = CONFIG$DB_CONFIG$user,
    password = CONFIG$DB_CONFIG$password
    )
fd::use_db(conn, CONFIG$DB_CONFIG$db)
db <- dplyr::tbl(conn, "spuls_standard_results")
d <- db %>% dplyr::filter(tag=="emerg1" & granularity_time=="weekly") %>% dplyr::collect()
setDT(d)

county <- d[granularity_geo =="county" | granularity_geo =="national"]
municip <- d[granularity_geo =="municip"]
county[,age:=factor(age,levels=names(CONFIG$AGES))]

county_year = county[date >=start_date]
municip_year = municip[date >=start_date]


```

\newpage

# Epi-curve

```{r echo=FALSE, fig.height=11.69*0.3, message=FALSE, warning=FALSE}
q <- ggplot(county_year[location=="Norge" & age == "Totalt"]) +
    geom_col(aes(x=date, y=n), fill = fhiplot::base_color, width = 4) +
    theme_fhi_lines() +
    ylab("") 
q
```

# County Map

```{r echo=FALSE, fig.height=11.69*0.3, message=FALSE, warning=FALSE}

pd <- fhidata::norway_map_counties

plot_data <- data.table(pd)[county_year[, .(N=sum(n)), by=.(location)], on=.(location_code=location), nomatch=0]
max <- max(plot_data$N)
plot_data[, binned := cut(N , round(max/5 * 0:5))]
q <- ggplot()
q <- q + geom_polygon(data = plot_data, aes( x = long, y = lat, group = group, fill=binned), color="black")
q <- q + theme_void()
q <- q + coord_quickmap()
q <- q + fhiplot::scale_fill_fhi("Cases", palette = "map_seq_complete", direction = 1) 
q

```

# Muncipalities with the most cases

```{r echo=FALSE, results='asis', paged.print=TRUE }

pop <- fhidata::norway_population_current

pop <- data.table(pop)[, .(pop=sum(pop)), by=.(location_code)]

municip_cases <- municip_year[,  .(N=sum(n)), by=.(location)][pop, on=.(location=location_code), nomatch=0]

municip_cases <- municip_cases[, .(location, N,  incidence = round(N / pop * 1000, 1))][data.table(fhi::NorwayLocations()), on=.(location=municip), nomatch=0]


table <- municip_cases[order(-N), .(municipName, N, incidence)][1:35]
 setnames(table,c(
    "Municipality","Cases","Incidence per 1000 inhabitants")

  )

  k <- knitr::kable(table, "latex",
                      booktabs = T,
                      align = "c",
                      linesep = "")
   print(k)


```
