---
title: "Statistics"
output:
  tufte::tufte_handout:
    toc: TRUE
    keep_tex: FALSE
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
  - \makeatletter\renewcommand*{\fps@figure}{H}\makeatother
params:
  dev: TRUE
  package_dir: "."
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
fhi::DashboardInitialiseOpinionated("sykdomspuls",
                                    PACKAGE_DIR=params$package_dir,
                                    FORCE_DEV_PACKAGE_LOAD = params$dev,
                                    SILENT=TRUE)

suppressMessages(library(data.table))
suppressMessages(library(ggplot2))
suppressMessages(library(kableExtra))


```

\newpage

# Time taken

```{r echo=FALSE, fig.height=11.69*0.6, message=FALSE, warning=FALSE}
  qs <- AnalyseLog()
```


## Overview

`r tufte::margin_note(glue::glue('
                                    We monitor the number of time taken to ensure that \
                                    there are no issues.
                                    '))`

```{r echo=FALSE, fig.height=11.69*0.6, message=FALSE, warning=FALSE}
  print(qs[["overview"]])
```

\newpage

## Details

```{r echo=FALSE,  fig.fullwidth=TRUE, fig.height=11.69*0.6, fig.width=8.27*0.9, message=FALSE, warning=FALSE}
  print(qs[["details"]])
```
