---
title: "Skabb"
output:
  tufte::tufte_handout:
    toc: TRUE
    keep_tex: TRUE
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
  - \makeatletter\renewcommand*{\fps@figure}{H}\makeatother
params:
  dev: TRUE
  package_dir: "."
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
fhi::DashboardInitialiseOpinionated("sykdomspuls",
                                    PACKAGE_DIR=params$package_dir,
                                    FORCE_DEV_PACKAGE_LOAD = params$dev,
                                    SILENT=TRUE)

suppressMessages(library(data.table))
suppressMessages(library(ggplot2))
suppressMessages(library(kableExtra))
conn <- DBI::dbConnect(odbc::odbc(),
    driver = CONFIG$DB_CONFIG$driver,
    server = CONFIG$DB_CONFIG$server,
    port = CONFIG$DB_CONFIG$port,
    user = CONFIG$DB_CONFIG$user,
    password = CONFIG$DB_CONFIG$password
    )
fd::use_db(conn, CONFIG$DB_CONFIG$db)
db <- dplyr::tbl(conn, "spuls_standard_results")
d <- db %>% dplyr::filter(location_code =="Norge" & tag=="skabb" & granularity_time=="weekly") %>%
    dplyr::select(location_code, age, date, n)  %>% dplyr::collect()
setDT(d)

d <- d[,age:=factor(age,levels=names(CONFIG$AGES))]

```

\newpage

# Norway

`r tufte::margin_note(glue::glue('
                                  Skabb at the national level.
                                  '))`

```{r echo=FALSE, fig.height=11.69*0.6, message=FALSE, warning=FALSE}
q <- ggplot(d, aes(x=date,y=n))
q <- q + geom_line()
q <- q + facet_wrap(~age,ncol=1)
q
```
