---
title: "Signals"
author: "Richard White"
date: "2018-10-12"
output:
  rmarkdown::html_vignette:
    self_contained: TRUE
    css:
      - !expr system.file("rmarkdown/templates/html_vignette/resources/vignette.css", package = "rmarkdown")
      - !expr system.file("ext", "style_vignettes.css", package = "fhi")
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(data.table)
library(ggplot2)

# Load raw data
d <- sykdomspuls::GenFakeDataRaw()
print(d)
```

```{r}
# Format the data into panel data
d <- sykdomspuls::FormatData(d,
    SYNDROME = "influensa",
    testIfHelligdagIndikatorFileIsOutdated = FALSE,
    removeMunicipsWithoutConsults = TRUE
  )
print(d)
```

```{r}
d <- d[age=="Totalt"]
print(d)
```

```{r}
setnames(d, "value", "n")
setnames(d, "consultWithInfluensa", "consult")
res <- sykdomspuls::QuasipoissonTrainPredictData(
  datasetTrain = d,
  datasetPredict = d,
  isDaily = F
)

print(res)
```








